import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "@/components/Menu/Menu";
import Header from "@/components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        <Header />
        <div className="flex flex-1 overflow-hidden">
          <Menu />
          <main className="flex-1 overflow-auto" style={{ backgroundColor: "#e8e8e8" }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
